// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[]  = "132892de-1201-4f90-8179-543411ff0a0c";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMoveChange();
void onLocChange();
void onRwChange();

int move;
CloudLocation loc;
bool rw;

double  Lat;
double  Long;


void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(move, READWRITE, ON_CHANGE, onMoveChange);
  ArduinoCloud.addProperty(loc, READWRITE, ON_CHANGE, onLocChange);
  ArduinoCloud.addProperty(rw, READWRITE, ON_CHANGE, onRwChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);